
name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: 
      - main
      - branchpull
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:
jobs:
  #permanent_actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
       ref: main
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Node version
      run: 'node -v'

    - name: Show directory
      run: 'ls -al'

    - name: Install Dependencies
      run: 'npm install'

    - name: Run tests
      run: 'npm test'
